title: LIVABLŌM
description: "Logements haut de gamme à Guesnain (Douaisis) : spa romantique BLŌM pour les couples & maison LIVA pour familles ou pros."
url: "https://livablom.github.io"
baseurl: "/LIVABLOM"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: pretty
include:
  - index.md
  - liva.md
  - blom.md
exclude:
  - README.md
  - .gitignore
google_analytics: "G-34YPEPJ0WQ"
