title: LIVABLŌM
description: "Logements haut de gamme à Guesnain (Douaisis) : spa romantique BLŌM pour les couples & maison LIVA pour familles ou pros."
url: "https://www.livablom.fr"
baseurl: ""
markdown: kramdown
theme: minima
production:
  backend_url: "https://livablom-stripe-production.up.railway.app"
development:
  backend_url: "http://localhost:3000"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: pretty
maintenance: false
include:
  - index.md
  - liva.md
  - blom.md
exclude:
  - README.md
  - .gitignore
google_analytics: "G-34YPEPJ0WQ"

