title: LIVABLŌM
description: "Location de logements haut de gamme : LIVA pour familles et pros, BLŌM pour les couples."
url: "https://livablom.github.io" # Adresse principale
baseurl: "/LIVABLOM"              # Nom du dépôt GitHub Pages
permalink: pretty
markdown: kramdown
theme: minima
# Force rebuild
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permet de générer des liens propres (sans .html)
permalink: pretty

# Exclure les fichiers inutiles pour le build
exclude:
  - README.md
  - .gitignore
